/*
 * This source file was generated by the Gradle 'init' task
 */
package com.arka.arkajjmunozm;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest
@ActiveProfiles("test")
class ArkaAppTest {
    @Test
    void contextLoads() {
    }
}
