/*
 * This source file was generated by the Gradle 'init' task
 */
package com.arka.arkajjmunozm;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@EnableEurekaServer
@SpringBootApplication
public class ArkaApp {
    public static void main(String[] args) {
        SpringApplication.run(ArkaApp.class, args);
    }
}
