spring.application.name=Arkajjmunozm

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/arkajjmunozm
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto del servidor
server.port=8080

#configuracion del microservicio
microservices.cotizador.url=http://localhost:8081

# Circuit Breaker
resilience4j.circuitbreaker.instances.cotizador.slidingWindowSize=10
resilience4j.circuitbreaker.instances.cotizador.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cotizador.waitDurationInOpenState=5000
