spring.application.name=Arkajjmunozm

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/arkajjmunozm
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de microservicios
microservices.cotizador.url=http://localhost:8080
microservices.gestor-solicitudes.url=http://localhost:8081

# Configuración de timeout para WebClient
microservices.timeout.connection=5000
microservices.timeout.read=10000

# Puerto del servidor principal
server.port=8082